from pyprojectviz.utils import parse_file, load_graph, generate_graph
from pyprojectviz.config import Configuration


def test_load_graph():
    config = Configuration()
    graph = load_graph(config.graphviz)
    assert graph.comment == "Generated by Pyprojectviz"


def test_parse_file():
    config = Configuration()
    graph = parse_file("tests/test_project/test_module.py", config)
    assert "test_module" in graph.body[0]


def test_generate_graph():
    config = Configuration()
    graph = generate_graph("tests/test_project", config)
    assert "test_module" in graph.body[1]
